### PR TITLE
Make query string parsing conform to URL spec

### LINKED ISSUE #1696: Change nested query parsing behavior of "foo[]" from {"foo" => [nil]} to {"foo" => []}
Hello lovely folks,

first and foremost thanks for your excellent work on this project practically the entire ruby webdev eco system relies on :green_heart: :tada: :rocket: 

## Problem

I've come here today to propose a change in the parsing behavior of the query string `param[]`.

There is a spec asserting the current behavior so I assume it's intentional
https://github.com/rack/rack/blob/649c72bab9e7b50d657b5b432d0c205c95c2be07/test/spec_utils.rb#L164-L165

I believe/hope the more correct test would be:

```ruby
    Rack::Utils.parse_nested_query("foo[]").
      must_equal "foo" => []
```

I base this on three things:

* we otherwise have no way to indicate an empty array and an array with `nil` doesn't seem particularly useful (or intuitive) vs. an empty array
* the introduction was 12 years ago (  6e330bdda5b003f4c2ed1b20af47c05c544 ) and might be a side effect of the implementation due to the splitting behavior exhibited here: https://github.com/rack/rack/blob/649c72bab9e7b50d657b5b432d0c205c95c2be07/lib/rack/query_parser.rb#L67-L72
* the popular HTTP client library faraday (which `her` and many projects rely upon) changed it's way of serializing empty arrays to the query string above https://github.com/lostisland/faraday/pull/801

Especially due to the last point this creates a sort of dissonance in the Ruby eco system where I send an empty array from the one side and it arrives as `[nil]` on the server side. Of course, the fix might also be on the faraday side.

I have not yet checked the HTTP specs or anything about this to see what's "officially correct"

To have complete traceability, I came here via https://github.com/ruby-grape/grape/issues/2079 :) 

## Implementation

I'm not sure if it's the complete implementation but it seems to be easily fixable in https://github.com/rack/rack/blob/649c72bab9e7b50d657b5b432d0c205c95c2be07/lib/rack/query_parser.rb#L102-L105

all it needs is `unless v.nil?`:

```ruby
      elsif after == "[]"
        params[k] ||= []
        raise ParameterTypeError, "expected Array (got #{params[k].class.name}) for param `#{k}'" unless params[k].is_a?(Array)
        params[k] << v unless v.nil?
```

All tests (with exception of the one mentioned above) pass with this change.

(I have the code, I found the old spec while implementing this/my spec was elsewhere)

Happy to make a PR should it be wanted!

Thanks for all your work! :tada: :rocket:

### PR DESCRIPTION
**Pull request by jeremyevans**
The URL spec section 5.1.3.3 specifies that if = is not present
in the byte sequence, it should be treated as if the byte sequence
is the name of the tuple and the value is the empty string.

This affects all parameters without =, not just arrays:

```ruby
Rack::Utils.parse_nested_query("foo[bar]&baz[]&quux")
{"foo"=>{"bar"=>nil}, "baz"=>[nil], "quux"=>nil} # Before
{"foo"=>{"bar"=>""}, "baz"=>[""], "quux"=>""}    # After
```

Fixes #1696

### CODE REVIEW

**Comment by ioquatix** [comment]
The implications of this change are:

1. Can no longer specify nil values in any way (maybe a good thing?)
2. Existing code that depends on nil may be broken in subtle ways.

**Comment by jeremyevans** [comment]
You are correct about the implications. In general, you should omit the parameter if it should have a nil value.  That's more of an implicit nil, this would remove the explicit nil.

Correct that this will change behavior and can break things that depend on nil values.  That's why I labeled it a breaking change in the CHANGELOG.

Looks like the result of `Rack::Utils.build_query({x: [nil, nil, nil]})` is bad.  It should be `x[]=&x[]=&x[]=` or `x[]&x[]&x[]` or the empty string (if we drop elements with nil values).  That's not strictly related to parsing, so it should probably be fixed in a separate pull request.  nil won't roundtrip through query parsing, but neither do empty arrays, empty hashes, numbers, booleans, etc.  Anything that needs more than what query parsing provides should probably use JSON.

A somewhat informal explanation of query parsing types using an algebraic data types:

A QueryParseResult (result of `Rack::Utils.parse_nested_query`) is a hash with String keys and QueryParseValue values.

A QueryParseValue is either a:

* String
* QueryParseResult
* Array of String|QueryParseResult

**Comment by ioquatix** [comment]
I basically agree with this but I'm concerned about the blast radius of this change.

File: lib/rack/query_parser.rb [hunk 1]
```diff
@@ -86,6 +86,7 @@ def normalize_params(params, name, v, depth)
       name =~ %r(\A[\[\]]*([^\[\]]+)\]*)
```
Comment (ioquatix) [inline lib/rack/query_parser.rb:86]: Do you think you can tidy up this parsing logic a bit? Using `$` variables concerns me a little.

**Review by ioquatix — APPROVED** [review]

File: lib/rack/query_parser.rb (hunk 1 above)
Comment (jeremyevans) [reply lib/rack/query_parser.rb:86]: I can, but I don't see the reason to do so in this PR.  It's better to keep the implementation the same as before.  After all, there are other `$` variables used elsewhere in the code, including later in this method.  If you would like to remove `$` variable usage, we should probably do that globally in a separate PR.
