### PR TITLE
Fix handling of empty cookies in MockResponse

### LINKED ISSUE #2201: MockRequest can't handle an empty cookie anymore
Executing
```ruby
Rack::MockRequest.new(->(env) { [200, { "Set-Cookie" => "" }, [""]] }).get("")
```
will fail with
> NoMethodError: undefined method `split' for nil
from /Users/foobar/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/rack-3.1.0/lib/rack/mock_response.rb:101:in `identify_cookie_attributes'

In earlier versions (<= 3.0.11) this used to work.

### PR DESCRIPTION
**Pull request by wynksaiddestroy**
Hopefully fixes #2201

### CODE REVIEW

File: lib/rack/mock_response.rb [hunk 1]
```diff
@@ -78,7 +78,7 @@ def cookie(name)
 
     def parse_cookies_from_header
       cookies = Hash.new
-      if headers.has_key? 'set-cookie'
+      if headers.has_key?('set-cookie') && !headers.fetch('set-cookie').empty?
         set_cookie_header = headers.fetch('set-cookie')
```
Comment (ioquatix) [inline lib/rack/mock_response.rb:82]:
```suggestion
      set_cookie_header = headers['set-cookie']
      if set_cookie_header&.any?
```

How about this? To avoid looking up the hash multiple times?

**Comment by ioquatix** [comment]
Can you please add an entry under `Fixed` in the changelog.

**Review by jeremyevans — APPROVED** [review]
Looks like I added a line to CHANGELOG while resolving the conflict in the web editor, but we can remove that later.

**Comment by ioquatix** [comment]
I’ll fix it it, merge and backport.

File: CHANGELOG.md [hunk 2]
```diff
@@ -30,6 +31,7 @@ All notable changes to this project will be documented in this file. For info on
 
 - Oops! I shouldn't have shipped that
 
+
```
Comment (ioquatix) [inline CHANGELOG.md:34]:
```suggestion
```
