### PR TITLE
Fix content-length calcuation in Rack:Response#write

### LINKED ISSUE #2148: Multiple writes to Rack::Response result in incorrect content-length header in Rack 3
## Problem

After upgrading to Rack 3, I found that `Rack::Response` generates an incorrect content-length header when:

- it is constructed with an empty array for the body, and
- `write` is called multiple times

Here is a simple reproduction script:

```ruby
require "rack"

status = 200
headers = {}
response = Rack::Response.new([], status, headers)

# Write 11 total bytes
response.write "hello"
response.write "world"
response.write "!"

# Resulting content-length should be 11, but is 26
response.headers
# => {"content-length"=>"26"}
```

## Underlying cause

When `Rack::Response` is constructed with an empty array, it sets this internal state:

https://github.com/rack/rack/blob/0cd4d40a759f3e68f13c0467091cf836d086e9a1/lib/rack/response.rb#L82

This causes the value of `@length` to accumulate on every call to `Rack::Response#write`:

https://github.com/rack/rack/blob/0cd4d40a759f3e68f13c0467091cf836d086e9a1/lib/rack/response.rb#L317-L323

When `chunked?` is `false`, `@length` is incremented yet again, and then emitted as a content-length header:

https://github.com/rack/rack/blob/0cd4d40a759f3e68f13c0467091cf836d086e9a1/lib/rack/response.rb#L348-L350

The result is that the content-length value is too large, and the error gets larger on every call to `write`.

### PR DESCRIPTION
**Pull request by mattbrictson**
When `Rack::Response` is initialized with an Array, it properly sets its internal `@length` value and emitted content-length header on the first use of `write`. But every subsequent time `write` is called, it increments the length incorrectly, resulting in an incorrect content-length header.

This commit fixes the accumulation bug, and fixes/adds specs to properly test the scenario where `write` is used multiple times.

Fixes #2148

### CODE REVIEW

File: test/spec_response.rb [hunk 1]
```diff
@@ -408,7 +408,7 @@ def object_with_each.each
     status.must_equal 404
   end
 
-  it "correctly updates content-type when writing when not initialized with body" do
+  it "correctly updates content-length when writing when initialized without body" do
```
Comment (mattbrictson) [inline test/spec_response.rb:411]: 🗒️ These specs incorrectly referred to `content-type`, but are actually testing `content-length`.

File: test/spec_response.rb [hunk 2]
```diff
@@ -419,20 +419,24 @@ def object_with_each.each
     header['content-length'].must_equal '9'
   end
 
-  it "correctly updates content-type when writing when initialized with body" do
-    obj = Object.new
-    def obj.each
-      yield 'foo'
-      yield 'bar'
-    end
-    ["foobar", ["foo", "bar"], obj].each do
```
Comment (mattbrictson) [inline test/spec_response.rb:428]: 🗒️ This `.each` doesn't appear to be doing anything useful. There is no block param, so each iteration is identical. I rewrote this spec to simplify it.

File: test/spec_response.rb [hunk 3]
```diff
@@ -419,20 +419,24 @@ def object_with_each.each
...
+    r = Rack::Response.new(["foo"])
+    r.write('bar')
+    r.write('baz')
+    _, header, body = r.finish
+    str = "".dup; body.each { |part| str << part }
+    str.must_equal "foobarbaz"
+    header['content-length'].must_equal '9'
+  end
+
+  it "correctly updates content-length when writing when initialized with String body" do
```
Comment (mattbrictson) [inline test/spec_response.rb:432]: 🗒️ Now there are 3 specs, covering all three branching conditions of the `Rack::Response` initializer:

1. `nil` body
2. Array body
3. String body

The Array case is what is fixed by this PR.

**Comment by mattbrictson** [comment]
The jruby CI failures seem unrelated?

File: test/spec_response.rb (hunk 3 above)
Comment (ioquatix) [reply test/spec_response.rb:432]: What about "Object that responds to `#each` body"?

Comment (mattbrictson) [reply test/spec_response.rb:432]: Good catch. I've added a test for that (see 578243c8) and then squashed to one commit.

**Comment by ioquatix** [comment]
Thanks for your contribution. @jeremyevans as this is a bug fix should we consider back porting to 3.0?

**Comment by jeremyevans** [comment]
Sure, this seems reasonable to backport.
